### ISSUE TITLE
Please create versions of this role

### ISSUE THREAD

**Issue by gswallow** [vkill/ansible-role-incron#8]
As an author of an Ansible playbook, I need to specify a version of this role to download using ansible-galaxy, rather than "master."  I can set up a specific git hash, if necessary but semantic versioning would be better.

**Comment by vkill** [comment]
Oh, please submit a PR, I haven't used ansbile for a long time.

**Comment by gswallow** [comment]
It's your repository.  I believe you have to create versions or tags but if
it's not going to change, then I won't pay attention :)
